### ISSUE TITLE
[WizFi Upgrade Tool]Change binary .img URL for Cloud update

### ISSUE THREAD

**Issue by taylor-an** [WIZnet-WizFi360/Release#4]
[WizFi Upgrade Tool]Change binary .img URL for Cloud update

**Comment by taylor-an** [comment]
URL :
https://github.com/WIZnet-WizFi360/Release/blob/master/Binary/WM_W600_GZ.img

**Comment by IssacWangWiznet** [comment]
hi taylor, as i remember , cloud update function is in the app , and WizFi Upgrade Tool may not find the new firmware on cloud, WizFi Upgrade Tool may just will use the firmware you select at your pc to set up a http file sever , and you can simplely use "AT+CIPUPDATE="xxx.xxx.xxx.xxx:xx/xxxxx.xx"" to finish update. for example, if my pc's ip is 192.168.1.101, and the name of firmware i selected is AT_SDK.bin , and i will send "AT+CIPUPDATE="192.168.1.101:8080/AT_SDK.bin"" ,module will try to find firmware by using  this URL. and if i just send "AT+CIPUPDATE" ,module will find the firmware on cloud instead of findind on your pc. so you can modify firmware to fix this issue.

advice to modify firmware i have sent to you on QQ , you can refer it.

**Comment by IssacWangWiznet** [comment]
hi taylor, i test 
URL :
https://github.com/WIZnet-WizFi360/Release/blob/master/Binary/WM_W600_GZ.img
but it go to a page , not a firmware

and i find a 
URL :
https://github.com/WIZnet-WizFi360/Release/raw/master/Binary/WM_W600_GZ.img
and it can work

so do you mean 
URL :
https://github.com/WIZnet-WizFi360/Release/raw/master/Binary/WM_W600_GZ.img

**Comment by IssacWangWiznet** [comment]
i also try the AT+CIPUPDATE ,but it may doesn't work
![image](https://user-images.githubusercontent.com/43438511/61517309-830c7400-aa39-11e9-852a-d7525d25f7b0.png)

**Comment by IssacWangWiznet** [comment]
and i think AT+CIPUPDATE="url" may be better for user to use, cause when user update, they can select the firmware from their server , and when the net is down, they can also use local wifi spot to set up a http file server for update. Since our WizFi Upgrade Tool use this way to provide update by wifi, so if user can't use AT+CIPUPDATE="url" with url so wifi update of WizFi Upgrade Tool may not work.

**Comment by taylor-an** [comment]
Moved this issue.
